_BASE_: maskdino_R50_bs16_50ep_3s_dowsample1_2048.yaml
INPUT:
  IMAGE_SIZE: 450
MODEL:
  SEM_SEG_HEAD:
    NUM_CLASSES: 1
  RETINANET:
    NUM_CLASSES: 1
SOLVER:
  BASE_LR: 0.0001
  MAX_ITER: 200000
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 60

